#!/usr/bin/env python3
"""
Visual dashboard for Metals Rotation Forward Paper.

Reads snapshots generated by bot.py.
PAPER ONLY — no real order functionality.
"""

import json
import os
from pathlib import Path

import pandas as pd
from flask import Flask, jsonify, render_template_string

app = Flask(__name__)

preferred = Path(os.getenv("DATA_DIR", "/data"))
DATA_DIR = preferred if preferred.exists() else Path(".").resolve()

SUMMARY = DATA_DIR / "metals_rotation_forward_summary.json"
TRADES = DATA_DIR / "metals_rotation_forward_trades.csv"
POSITIONS = DATA_DIR / "metals_rotation_forward_positions.csv"
EXPOSURE = DATA_DIR / "metals_rotation_forward_exposure.csv"


HTML = r"""
<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="refresh" content="60">
<title>Mi Bot Metales — Rotation</title>
<style>
:root{
  --bg:#071018; --card:#0d1722; --line:#263545; --muted:#9aa8b9;
  --text:#f3f6fa; --green:#59e5a7; --red:#ff7188; --yellow:#ffd166;
  --blue:#69a7ff;
}
*{box-sizing:border-box}
body{
  margin:0;background:var(--bg);color:var(--text);
  font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;
}
.wrap{max-width:920px;margin:auto;padding:24px 18px 60px}
.header{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:28px}
h1{font-size:clamp(34px,6vw,54px);margin:0 0 6px;font-weight:500}
.sub{font-size:clamp(19px,3vw,29px);color:var(--muted)}
.badge{
  white-space:nowrap;padding:18px 28px;border-radius:999px;
  background:#103f2f;color:var(--green);font-size:20px
}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}
.card{
  background:var(--card);border:1px solid var(--line);border-radius:26px;
  padding:28px 30px;margin-bottom:18px
}
.label{color:var(--muted);font-size:24px;margin-bottom:18px}
.big{font-size:48px;line-height:1.05}
.smallvalue{font-size:22px;margin-top:10px}
.green{color:var(--green)} .red{color:var(--red)} .yellow{color:var(--yellow)}
.kpis{font-size:28px;line-height:1.55}
.positions{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}
.pos{
  border:1px solid var(--line);border-radius:18px;padding:18px;background:#0a141e
}
.pos strong{font-size:23px}
.muted{color:var(--muted)}
table{width:100%;border-collapse:collapse;font-size:19px}
th,td{padding:15px 8px;border-bottom:1px solid var(--line);text-align:left}
th{color:var(--muted);font-weight:500}
.progress{height:12px;background:#172433;border-radius:20px;overflow:hidden;margin:12px 0}
.progress>div{height:100%;background:var(--green)}
.chips{display:flex;flex-wrap:wrap;gap:10px}
.chip{padding:10px 14px;border:1px solid var(--line);border-radius:999px;background:#0a141e}
.notice{font-size:18px;color:var(--muted);line-height:1.55}
@media(max-width:650px){
  .grid{grid-template-columns:1fr 1fr;gap:12px}
  .card{padding:22px 20px;border-radius:22px}
  .big{font-size:38px}.label{font-size:20px}.kpis{font-size:23px}
  .badge{padding:14px 18px;font-size:17px}
  table{font-size:16px}
}
</style>
</head>
<body>
<div class="wrap">
  <div class="header">
    <div>
      <h1>Mi Bot Metales</h1>
      <div class="sub">Paper trading · Rotación cuantitativa</div>
    </div>
    <div class="badge">● ONLINE</div>
  </div>

  {% if not ready %}
    <div class="card">
      <div class="label">Estado</div>
      <div class="big yellow">Preparando datos…</div>
      <p class="notice">El worker está generando el primer snapshot del nuevo sistema. Actualiza en unos minutos.</p>
    </div>
  {% else %}

  <div class="grid">
    <div class="card">
      <div class="label">Saldo total</div>
      <div class="big">{{ "%.2f"|format(s.current_equity_eur) }} €</div>
      <div class="smallvalue {{ 'green' if s.total_return_pct >= 0 else 'red' }}">
        Resultado: {{ "%+.2f"|format(s.current_equity_eur - s.starting_capital_eur) }} €
        ({{ "%+.2f"|format(s.total_return_pct) }}%)
      </div>
    </div>
    <div class="card">
      <div class="label">Efectivo</div>
      <div class="big">{{ "%.2f"|format(s.cash_eur) }} €</div>
      <div class="smallvalue muted">Capital inicial: {{ "%.2f"|format(s.starting_capital_eur) }} €</div>
    </div>
  </div>

  <div class="card">
    <div class="label">Posiciones abiertas · {{ s.open_positions }}</div>
    {% if positions %}
      <div class="positions">
      {% for p in positions %}
        <div class="pos">
          <strong>{{ p.symbol }}</strong><br>
          <span class="muted">Entrada {{ p.entry_date }}</span><br>
          Valor: {{ "%.2f"|format(p.market_value) }} €<br>
          <span class="{{ 'green' if p.unrealized_pnl_if_closed_now >= 0 else 'red' }}">
            PnL: {{ "%+.2f"|format(p.unrealized_pnl_if_closed_now) }} €
          </span>
        </div>
      {% endfor %}
      </div>
    {% else %}
      <div class="kpis">Sin posiciones abiertas</div>
    {% endif %}
  </div>

  <div class="card">
    <div class="label">Rendimiento forward</div>
    <div class="kpis">
      Periodos cerrados: <b>{{ s.closed_trades }}</b><br>
      Ganadas: <b>{{ wins }}</b> · Perdidas: <b>{{ losses }}</b><br>
      Acierto: <b>{{ "%.1f"|format(s.win_rate_pct) }}%</b><br>
      Profit Factor: <b>{{ "%.3f"|format(s.profit_factor) }}</b><br>
      PnL realizado:
      <b class="{{ 'green' if s.realized_pnl >= 0 else 'red' }}">{{ "%+.2f"|format(s.realized_pnl) }} €</b><br>
      Drawdown máximo: <b>{{ "%.2f"|format(s.max_drawdown_pct) }}%</b>
    </div>
  </div>

  <div class="card">
    <div class="label">Sistema congelado</div>
    <div class="chips">
      <span class="chip">Top 4 activos</span>
      <span class="chip">Rebalance 21 sesiones</span>
      <span class="chip">Vol objetivo 6%</span>
      <span class="chip">Sin apalancamiento</span>
      <span class="chip">SPY filtro 200d</span>
    </div>
    <p class="notice">
      Universo: ETFs de metales/minería, mineras y grandes acciones líquidas.
      El capital no utilizado permanece en efectivo.
    </p>
  </div>

  <div class="card">
    <div class="label">Próximo rebalance / exposición</div>
    {% if pending %}
      <div class="kpis">
        Señal: <b>{{ pending.signal_date }}</b><br>
        Exposición objetivo: <b>{{ "%.1f"|format(pending.gross_exposure * 100) }}%</b><br>
        Selección:
      </div>
      <div class="chips" style="margin-top:14px">
        {% for sym in pending.symbols %}
          <span class="chip">{{ sym }}</span>
        {% endfor %}
      </div>
    {% else %}
      <div class="kpis">Sin rebalance pendiente</div>
    {% endif %}
  </div>

  <div class="card">
    <div class="label">Gate de forward</div>
    <div class="kpis">
      Meses: <b>{{ "%.2f"|format(s.months_elapsed) }} / 6</b>
      <div class="progress"><div style="width:{{ month_pct }}%"></div></div>
      Periodos: <b>{{ s.closed_trades }} / 40</b>
      <div class="progress"><div style="width:{{ trade_pct }}%"></div></div>
      Estado:
      <b class="{{ 'green' if s.forward_gate['pass'] else 'yellow' }}">
        {{ 'PASS' if s.forward_gate['pass'] else 'AÚN NO' }}
      </b>
    </div>
  </div>

  <div class="card">
    <div class="label">Últimas operaciones</div>
    {% if trades %}
      <div style="overflow-x:auto">
      <table>
        <thead><tr><th>Activo</th><th>Entrada</th><th>Salida</th><th>PnL</th></tr></thead>
        <tbody>
        {% for t in trades %}
          <tr>
            <td>{{ t.symbol }}</td>
            <td>{{ t.entry_date }}</td>
            <td>{{ t.exit_date }}</td>
            <td class="{{ 'green' if t.net_pnl >= 0 else 'red' }}">{{ "%+.2f"|format(t.net_pnl) }} €</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
    {% else %}
      <div class="kpis">Aún no hay operaciones cerradas</div>
    {% endif %}
  </div>

  <div class="card">
    <div class="notice">
      <b>PAPER ONLY.</b> Este panel no tiene conexión a un bróker y no puede enviar órdenes reales.
      Forward iniciado el {{ s.forward_start }}. Último dato de mercado: {{ s.latest_market_date or "pendiente" }}.
      Actualización automática del panel cada 60 segundos.
    </div>
  </div>
  {% endif %}
</div>
</body>
</html>
"""


def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def read_csv(path):
    try:
        if not path.exists() or path.stat().st_size == 0:
            return []
        df = pd.read_csv(path)
        if df.empty:
            return []
        return df.replace({float("nan"): None}).to_dict("records")
    except Exception:
        return []


@app.route("/")
def index():
    s = read_json(SUMMARY)

    if not s:
        return render_template_string(HTML, ready=False)

    positions = read_csv(POSITIONS)
    trades = read_csv(TRADES)
    trades = trades[-8:][::-1]

    wins = sum(1 for t in read_csv(TRADES) if float(t.get("net_pnl", 0) or 0) > 0)
    losses = sum(1 for t in read_csv(TRADES) if float(t.get("net_pnl", 0) or 0) < 0)

    month_pct = min(100, max(0, float(s.get("months_elapsed", 0)) / 6 * 100))
    trade_pct = min(100, max(0, int(s.get("closed_trades", 0)) / 40 * 100))

    return render_template_string(
        HTML,
        ready=True,
        s=s,
        positions=positions,
        trades=trades,
        wins=wins,
        losses=losses,
        pending=s.get("pending_rebalance"),
        month_pct=month_pct,
        trade_pct=trade_pct,
    )


@app.route("/api/status")
def api_status():
    s = read_json(SUMMARY)
    return jsonify(s or {"status": "waiting_for_first_snapshot"})


@app.route("/health")
def health():
    return jsonify({"status": "ok", "paper_only": True})


if __name__ == "__main__":
    port = int(os.getenv("PORT", "8080"))
    app.run(host="0.0.0.0", port=port, debug=False)
